// Сгенерировано tool/gen_currency.dart (M3-шаг 2) из
// официального ISO 4217; руками не редактировать — править
// данные и перегенерировать. Часть полного списка ISO 4217:
// записи без широкой практики наличного обращения исключены,
// см. отчёт шага.

import 'package:kopilka/core/currency.dart';

/// Полный встроенный список ISO 4217 (157 записей):
/// код, символ, ISO-экспонент (0/2/3), английское название (D-15).
const List<CurrencyInfo> isoCurrencies = <CurrencyInfo>[
  CurrencyInfo(code: 'AED', symbol: 'د.إ', exponent: 2, nameEn: 'UAE Dirham'),
  CurrencyInfo(code: 'AFN', symbol: '؋', exponent: 2, nameEn: 'Afghani'),
  CurrencyInfo(code: 'ALL', symbol: 'L', exponent: 2, nameEn: 'Lek'),
  CurrencyInfo(code: 'AMD', symbol: '֏', exponent: 2, nameEn: 'Armenian Dram'),
  CurrencyInfo(
    code: 'ANG',
    symbol: 'ƒ',
    exponent: 2,
    nameEn: 'Netherlands Antillean Guilder',
  ),
  CurrencyInfo(code: 'AOA', symbol: 'Kz', exponent: 2, nameEn: 'Kwanza'),
  CurrencyInfo(
    code: 'ARS',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Argentine Peso',
  ),
  CurrencyInfo(
    code: 'AUD',
    symbol: 'A\$',
    exponent: 2,
    nameEn: 'Australian Dollar',
  ),
  CurrencyInfo(code: 'AWG', symbol: 'ƒ', exponent: 2, nameEn: 'Aruban Florin'),
  CurrencyInfo(
    code: 'AZN',
    symbol: '₼',
    exponent: 2,
    nameEn: 'Azerbaijan Manat',
  ),
  CurrencyInfo(
    code: 'BAM',
    symbol: 'KM',
    exponent: 2,
    nameEn: 'Convertible Mark',
  ),
  CurrencyInfo(
    code: 'BBD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Barbados Dollar',
  ),
  CurrencyInfo(code: 'BDT', symbol: '৳', exponent: 2, nameEn: 'Taka'),
  CurrencyInfo(
    code: 'BGN',
    symbol: 'лв.',
    exponent: 2,
    nameEn: 'Bulgarian Lev',
  ),
  CurrencyInfo(
    code: 'BHD',
    symbol: 'د.ب',
    exponent: 3,
    nameEn: 'Bahraini Dinar',
  ),
  CurrencyInfo(
    code: 'BIF',
    symbol: 'FBu',
    exponent: 0,
    nameEn: 'Burundi Franc',
  ),
  CurrencyInfo(
    code: 'BMD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Bermudian Dollar',
  ),
  CurrencyInfo(code: 'BND', symbol: '\$', exponent: 2, nameEn: 'Brunei Dollar'),
  CurrencyInfo(code: 'BOB', symbol: 'Bs', exponent: 2, nameEn: 'Boliviano'),
  CurrencyInfo(
    code: 'BRL',
    symbol: 'R\$',
    exponent: 2,
    nameEn: 'Brazilian Real',
  ),
  CurrencyInfo(
    code: 'BSD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Bahamian Dollar',
  ),
  CurrencyInfo(code: 'BTN', symbol: 'Nu.', exponent: 2, nameEn: 'Ngultrum'),
  CurrencyInfo(code: 'BWP', symbol: 'P', exponent: 2, nameEn: 'Pula'),
  CurrencyInfo(
    code: 'BYN',
    symbol: 'Br',
    exponent: 2,
    nameEn: 'Belarusian Ruble',
  ),
  CurrencyInfo(code: 'BZD', symbol: '\$', exponent: 2, nameEn: 'Belize Dollar'),
  CurrencyInfo(
    code: 'CAD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Canadian Dollar',
  ),
  CurrencyInfo(
    code: 'CDF',
    symbol: 'FC',
    exponent: 2,
    nameEn: 'Congolese Franc',
  ),
  CurrencyInfo(code: 'CHF', symbol: 'Fr.', exponent: 2, nameEn: 'Swiss Franc'),
  CurrencyInfo(code: 'CLP', symbol: '\$', exponent: 0, nameEn: 'Chilean Peso'),
  CurrencyInfo(code: 'CNY', symbol: '¥', exponent: 2, nameEn: 'Yuan Renminbi'),
  CurrencyInfo(
    code: 'COP',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Colombian Peso',
  ),
  CurrencyInfo(
    code: 'CRC',
    symbol: '₡',
    exponent: 2,
    nameEn: 'Costa Rican Colon',
  ),
  CurrencyInfo(code: 'CUP', symbol: '\$', exponent: 2, nameEn: 'Cuban Peso'),
  CurrencyInfo(
    code: 'CVE',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Cabo Verde Escudo',
  ),
  CurrencyInfo(code: 'CZK', symbol: 'Kč', exponent: 2, nameEn: 'Czech Koruna'),
  CurrencyInfo(
    code: 'DJF',
    symbol: 'Fdj',
    exponent: 0,
    nameEn: 'Djibouti Franc',
  ),
  CurrencyInfo(code: 'DKK', symbol: 'kr.', exponent: 2, nameEn: 'Danish Krone'),
  CurrencyInfo(
    code: 'DOP',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Dominican Peso',
  ),
  CurrencyInfo(
    code: 'DZD',
    symbol: 'د.ج',
    exponent: 2,
    nameEn: 'Algerian Dinar',
  ),
  CurrencyInfo(
    code: 'EGP',
    symbol: 'E£',
    exponent: 2,
    nameEn: 'Egyptian Pound',
  ),
  CurrencyInfo(code: 'ERN', symbol: 'Nfk', exponent: 2, nameEn: 'Nakfa'),
  CurrencyInfo(
    code: 'ETB',
    symbol: 'Br',
    exponent: 2,
    nameEn: 'Ethiopian Birr',
  ),
  CurrencyInfo(code: 'EUR', symbol: '€', exponent: 2, nameEn: 'Euro'),
  CurrencyInfo(code: 'FJD', symbol: '\$', exponent: 2, nameEn: 'Fiji Dollar'),
  CurrencyInfo(
    code: 'FKP',
    symbol: '£',
    exponent: 2,
    nameEn: 'Falkland Islands Pound',
  ),
  CurrencyInfo(code: 'GBP', symbol: '£', exponent: 2, nameEn: 'Pound Sterling'),
  CurrencyInfo(code: 'GEL', symbol: '₾', exponent: 2, nameEn: 'Lari'),
  CurrencyInfo(code: 'GHS', symbol: '₵', exponent: 2, nameEn: 'Ghana Cedi'),
  CurrencyInfo(
    code: 'GIP',
    symbol: '£',
    exponent: 2,
    nameEn: 'Gibraltar Pound',
  ),
  CurrencyInfo(code: 'GMD', symbol: 'D', exponent: 2, nameEn: 'Dalasi'),
  CurrencyInfo(code: 'GNF', symbol: 'FG', exponent: 0, nameEn: 'Guinean Franc'),
  CurrencyInfo(code: 'GTQ', symbol: 'Q', exponent: 2, nameEn: 'Quetzal'),
  CurrencyInfo(code: 'GYD', symbol: '\$', exponent: 2, nameEn: 'Guyana Dollar'),
  CurrencyInfo(
    code: 'HKD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Hong Kong Dollar',
  ),
  CurrencyInfo(code: 'HNL', symbol: 'L', exponent: 2, nameEn: 'Lempira'),
  CurrencyInfo(code: 'HRK', symbol: 'kn', exponent: 2, nameEn: 'Kuna'),
  CurrencyInfo(code: 'HTG', symbol: 'G', exponent: 2, nameEn: 'Gourde'),
  CurrencyInfo(code: 'HUF', symbol: 'Ft', exponent: 2, nameEn: 'Forint'),
  CurrencyInfo(code: 'IDR', symbol: 'Rp', exponent: 2, nameEn: 'Rupiah'),
  CurrencyInfo(
    code: 'ILS',
    symbol: '₪',
    exponent: 2,
    nameEn: 'New Israeli Sheqel',
  ),
  CurrencyInfo(code: 'INR', symbol: '₹', exponent: 2, nameEn: 'Indian Rupee'),
  CurrencyInfo(code: 'IQD', symbol: 'ع.د', exponent: 3, nameEn: 'Iraqi Dinar'),
  CurrencyInfo(code: 'IRR', symbol: '﷼', exponent: 2, nameEn: 'Iranian Rial'),
  CurrencyInfo(code: 'ISK', symbol: 'kr', exponent: 0, nameEn: 'Iceland Krona'),
  CurrencyInfo(
    code: 'JMD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Jamaican Dollar',
  ),
  CurrencyInfo(
    code: 'JOD',
    symbol: 'د.ا',
    exponent: 3,
    nameEn: 'Jordanian Dinar',
  ),
  CurrencyInfo(code: 'JPY', symbol: '¥', exponent: 0, nameEn: 'Japanese Yen'),
  CurrencyInfo(
    code: 'KES',
    symbol: 'KSh',
    exponent: 2,
    nameEn: 'Kenyan Shilling',
  ),
  CurrencyInfo(code: 'KGS', symbol: 'с', exponent: 2, nameEn: 'Som'),
  CurrencyInfo(code: 'KHR', symbol: '៛', exponent: 2, nameEn: 'Riel'),
  CurrencyInfo(
    code: 'KMF',
    symbol: 'CF',
    exponent: 0,
    nameEn: 'Comorian Franc',
  ),
  CurrencyInfo(
    code: 'KPW',
    symbol: '₩',
    exponent: 0,
    nameEn: 'North Korean Won',
  ),
  CurrencyInfo(code: 'KRW', symbol: '₩', exponent: 0, nameEn: 'Won'),
  CurrencyInfo(
    code: 'KWD',
    symbol: 'د.ك',
    exponent: 3,
    nameEn: 'Kuwaiti Dinar',
  ),
  CurrencyInfo(
    code: 'KYD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Cayman Islands Dollar',
  ),
  CurrencyInfo(code: 'KZT', symbol: '₸', exponent: 2, nameEn: 'Tenge'),
  CurrencyInfo(code: 'LAK', symbol: '₭', exponent: 2, nameEn: 'Lao Kip'),
  CurrencyInfo(
    code: 'LBP',
    symbol: 'ل.ل',
    exponent: 2,
    nameEn: 'Lebanese Pound',
  ),
  CurrencyInfo(
    code: 'LKR',
    symbol: 'Rs',
    exponent: 2,
    nameEn: 'Sri Lanka Rupee',
  ),
  CurrencyInfo(
    code: 'LRD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Liberian Dollar',
  ),
  CurrencyInfo(code: 'LSL', symbol: 'L', exponent: 2, nameEn: 'Loti'),
  CurrencyInfo(code: 'LYD', symbol: 'ل.د', exponent: 3, nameEn: 'Libyan Dinar'),
  CurrencyInfo(
    code: 'MAD',
    symbol: 'د.م.',
    exponent: 2,
    nameEn: 'Moroccan Dirham',
  ),
  CurrencyInfo(code: 'MDL', symbol: 'L', exponent: 2, nameEn: 'Moldovan Leu'),
  CurrencyInfo(
    code: 'MGA',
    symbol: 'Ar',
    exponent: 2,
    nameEn: 'Malagasy Ariary',
  ),
  CurrencyInfo(code: 'MKD', symbol: 'ден', exponent: 2, nameEn: 'Denar'),
  CurrencyInfo(code: 'MMK', symbol: 'K', exponent: 2, nameEn: 'Kyat'),
  CurrencyInfo(code: 'MNT', symbol: '₮', exponent: 2, nameEn: 'Tugrik'),
  CurrencyInfo(code: 'MOP', symbol: 'MOP\$', exponent: 2, nameEn: 'Pataca'),
  CurrencyInfo(
    code: 'MRU',
    symbol: 'UM',
    exponent: 2,
    nameEn: 'Mauritania Ouguiya',
  ),
  CurrencyInfo(
    code: 'MUR',
    symbol: 'Rs',
    exponent: 2,
    nameEn: 'Mauritius Rupee',
  ),
  CurrencyInfo(code: 'MVR', symbol: 'Rf', exponent: 2, nameEn: 'Rufiyaa'),
  CurrencyInfo(code: 'MWK', symbol: 'MK', exponent: 2, nameEn: 'Malawi Kwacha'),
  CurrencyInfo(code: 'MXN', symbol: '\$', exponent: 2, nameEn: 'Mexican Peso'),
  CurrencyInfo(
    code: 'MYR',
    symbol: 'RM',
    exponent: 2,
    nameEn: 'Malaysian Ringgit',
  ),
  CurrencyInfo(
    code: 'MZN',
    symbol: 'MT',
    exponent: 2,
    nameEn: 'Mozambique Metical',
  ),
  CurrencyInfo(
    code: 'NAD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Namibia Dollar',
  ),
  CurrencyInfo(code: 'NGN', symbol: '₦', exponent: 2, nameEn: 'Naira'),
  CurrencyInfo(code: 'NIO', symbol: 'C\$', exponent: 2, nameEn: 'Cordoba Oro'),
  CurrencyInfo(
    code: 'NOK',
    symbol: 'kr',
    exponent: 2,
    nameEn: 'Norwegian Krone',
  ),
  CurrencyInfo(
    code: 'NPR',
    symbol: 'रू',
    exponent: 2,
    nameEn: 'Nepalese Rupee',
  ),
  CurrencyInfo(
    code: 'NZD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'New Zealand Dollar',
  ),
  CurrencyInfo(code: 'OMR', symbol: 'ر.ع.', exponent: 3, nameEn: 'Rial Omani'),
  CurrencyInfo(code: 'PAB', symbol: 'B/.', exponent: 2, nameEn: 'Balboa'),
  CurrencyInfo(code: 'PEN', symbol: 'S/', exponent: 2, nameEn: 'Sol'),
  CurrencyInfo(code: 'PGK', symbol: 'K', exponent: 2, nameEn: 'Kina'),
  CurrencyInfo(
    code: 'PHP',
    symbol: '₱',
    exponent: 2,
    nameEn: 'Philippine Peso',
  ),
  CurrencyInfo(
    code: 'PKR',
    symbol: 'Rs',
    exponent: 2,
    nameEn: 'Pakistan Rupee',
  ),
  CurrencyInfo(code: 'PLN', symbol: 'zł', exponent: 2, nameEn: 'Zloty'),
  CurrencyInfo(code: 'PYG', symbol: '₲', exponent: 0, nameEn: 'Guarani'),
  CurrencyInfo(code: 'QAR', symbol: 'ر.ق', exponent: 2, nameEn: 'Qatari Rial'),
  CurrencyInfo(code: 'RON', symbol: 'lei', exponent: 2, nameEn: 'Romanian Leu'),
  CurrencyInfo(
    code: 'RSD',
    symbol: 'дин.',
    exponent: 2,
    nameEn: 'Serbian Dinar',
  ),
  CurrencyInfo(code: 'RUB', symbol: '₽', exponent: 2, nameEn: 'Russian Ruble'),
  CurrencyInfo(code: 'RWF', symbol: 'FRw', exponent: 0, nameEn: 'Rwanda Franc'),
  CurrencyInfo(code: 'SAR', symbol: 'ر.س', exponent: 2, nameEn: 'Saudi Riyal'),
  CurrencyInfo(
    code: 'SBD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Solomon Islands Dollar',
  ),
  CurrencyInfo(
    code: 'SCR',
    symbol: 'Rs',
    exponent: 2,
    nameEn: 'Seychelles Rupee',
  ),
  CurrencyInfo(
    code: 'SDG',
    symbol: 'ج.س.',
    exponent: 2,
    nameEn: 'Sudanese Pound',
  ),
  CurrencyInfo(code: 'SEK', symbol: 'kr', exponent: 2, nameEn: 'Swedish Krona'),
  CurrencyInfo(
    code: 'SGD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Singapore Dollar',
  ),
  CurrencyInfo(
    code: 'SHP',
    symbol: '£',
    exponent: 2,
    nameEn: 'Saint Helena Pound',
  ),
  CurrencyInfo(code: 'SLE', symbol: 'Le', exponent: 2, nameEn: 'Leone'),
  CurrencyInfo(
    code: 'SOS',
    symbol: 'Sh',
    exponent: 2,
    nameEn: 'Somali Shilling',
  ),
  CurrencyInfo(
    code: 'SRD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Surinam Dollar',
  ),
  CurrencyInfo(
    code: 'SSP',
    symbol: '£',
    exponent: 2,
    nameEn: 'South Sudanese Pound',
  ),
  CurrencyInfo(code: 'STN', symbol: 'Db', exponent: 2, nameEn: 'Dobra'),
  CurrencyInfo(
    code: 'SVC',
    symbol: '₡',
    exponent: 2,
    nameEn: 'El Salvador Colon',
  ),
  CurrencyInfo(code: 'SYP', symbol: '£S', exponent: 2, nameEn: 'Syrian Pound'),
  CurrencyInfo(code: 'SZL', symbol: 'E', exponent: 2, nameEn: 'Lilangeni'),
  CurrencyInfo(code: 'THB', symbol: '฿', exponent: 2, nameEn: 'Baht'),
  CurrencyInfo(code: 'TJS', symbol: 'SM', exponent: 2, nameEn: 'Somoni'),
  CurrencyInfo(
    code: 'TMT',
    symbol: 'm',
    exponent: 2,
    nameEn: 'Turkmenistan New Manat',
  ),
  CurrencyInfo(
    code: 'TND',
    symbol: 'د.ت',
    exponent: 3,
    nameEn: 'Tunisian Dinar',
  ),
  CurrencyInfo(code: 'TOP', symbol: 'T\$', exponent: 2, nameEn: 'Pa\'anga'),
  CurrencyInfo(code: 'TRY', symbol: '₺', exponent: 2, nameEn: 'Turkish Lira'),
  CurrencyInfo(
    code: 'TTD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'Trinidad and Tobago Dollar',
  ),
  CurrencyInfo(
    code: 'TWD',
    symbol: 'NT\$',
    exponent: 2,
    nameEn: 'New Taiwan Dollar',
  ),
  CurrencyInfo(
    code: 'TZS',
    symbol: 'TSh',
    exponent: 2,
    nameEn: 'Tanzanian Shilling',
  ),
  CurrencyInfo(code: 'UAH', symbol: '₴', exponent: 2, nameEn: 'Hryvnia'),
  CurrencyInfo(
    code: 'UGX',
    symbol: 'USh',
    exponent: 0,
    nameEn: 'Uganda Shilling',
  ),
  CurrencyInfo(code: 'USD', symbol: '\$', exponent: 2, nameEn: 'US Dollar'),
  CurrencyInfo(code: 'UYU', symbol: '\$', exponent: 2, nameEn: 'Peso Uruguayo'),
  CurrencyInfo(
    code: 'UZS',
    symbol: 'сум',
    exponent: 2,
    nameEn: 'Uzbekistan Sum',
  ),
  CurrencyInfo(
    code: 'VED',
    symbol: 'Bs.',
    exponent: 2,
    nameEn: 'Venezuelan Bolivar Soberano',
  ),
  CurrencyInfo(
    code: 'VES',
    symbol: 'Bs.',
    exponent: 2,
    nameEn: 'Venezuelan Bolivar Soberano',
  ),
  CurrencyInfo(code: 'VND', symbol: '₫', exponent: 0, nameEn: 'Dong'),
  CurrencyInfo(code: 'VUV', symbol: 'VT', exponent: 0, nameEn: 'Vatu'),
  CurrencyInfo(code: 'WST', symbol: 'T', exponent: 2, nameEn: 'Tala'),
  CurrencyInfo(
    code: 'XAF',
    symbol: 'FCFA',
    exponent: 0,
    nameEn: 'CFA Franc BEAC',
  ),
  CurrencyInfo(
    code: 'XCD',
    symbol: '\$',
    exponent: 2,
    nameEn: 'East Caribbean Dollar',
  ),
  CurrencyInfo(
    code: 'XOF',
    symbol: 'CFA',
    exponent: 0,
    nameEn: 'CFA Franc BCEAO',
  ),
  CurrencyInfo(code: 'XPF', symbol: '₣', exponent: 0, nameEn: 'CFP Franc'),
  CurrencyInfo(code: 'YER', symbol: '﷼', exponent: 2, nameEn: 'Yemeni Rial'),
  CurrencyInfo(code: 'ZAR', symbol: 'R', exponent: 2, nameEn: 'Rand'),
  CurrencyInfo(
    code: 'ZMW',
    symbol: 'ZK',
    exponent: 2,
    nameEn: 'Zambian Kwacha',
  ),
  CurrencyInfo(
    code: 'ZWL',
    symbol: 'Z\$',
    exponent: 2,
    nameEn: 'Zimbabwe Dollar',
  ),
];

/// Русские названия валют (D-23): константный словарь рядом
/// с ISO-списком, по одному на каждую запись списка.
const Map<String, String> currencyNamesRu = <String, String>{
  'AED': 'Дирхам (ОАЭ)',
  'AFN': 'Афгани',
  'ALL': 'Лек',
  'AMD': 'Армянский драм',
  'ANG': 'Гульдер Нидерландских Антилл',
  'AOA': 'Кванза',
  'ARS': 'Аргентинское песо',
  'AUD': 'Австралийский доллар',
  'AWG': 'Флорин Арубы',
  'AZN': 'Азербайджанский манат',
  'BAM': 'Конвертируемая марка',
  'BBD': 'Барбадосский доллар',
  'BDT': 'Така',
  'BGN': 'Болгарский лев',
  'BHD': 'Бахрейнский динар',
  'BIF': 'Бурундийский франк',
  'BMD': 'Бермудский доллар',
  'BND': 'Брунейский доллар',
  'BOB': 'Боливиано',
  'BRL': 'Бразильский реал',
  'BSD': 'Багамский доллар',
  'BTN': 'Нгултрум',
  'BWP': 'Пула',
  'BYN': 'Белорусский рубль',
  'BZD': 'Белизский доллар',
  'CAD': 'Канадский доллар',
  'CDF': 'Конголезский франк',
  'CHF': 'Швейцарский франк',
  'CLP': 'Чилийское песо',
  'CNY': 'Юань',
  'COP': 'Колумбийское песо',
  'CRC': 'Костариканский колон',
  'CUP': 'Кубинское песо',
  'CVE': 'Эскудо Кабо-Верде',
  'CZK': 'Чешская крона',
  'DJF': 'Франк Джибути',
  'DKK': 'Датская крона',
  'DOP': 'Доминиканское песо',
  'DZD': 'Алжирский динар',
  'EGP': 'Египетский фунт',
  'ERN': 'Накфа',
  'ETB': 'Эфиопский быр',
  'EUR': 'Евро',
  'FJD': 'Доллар Фиджи',
  'FKP': 'Фунт Фолклендских островов',
  'GBP': 'Фунт стерлингов',
  'GEL': 'Лари',
  'GHS': 'Ганский седи',
  'GIP': 'Гибралтарский фунт',
  'GMD': 'Даласи',
  'GNF': 'Гвинейский франк',
  'GTQ': 'Кетсаль',
  'GYD': 'Гайанский доллар',
  'HKD': 'Гонконгский доллар',
  'HNL': 'Лемпира',
  'HRK': 'Куна',
  'HTG': 'Гурд',
  'HUF': 'Форинт',
  'IDR': 'Рупия',
  'ILS': 'Новый израильский шекель',
  'INR': 'Индийская рупия',
  'IQD': 'Иракский динар',
  'IRR': 'Иранский риал',
  'ISK': 'Исландская крона',
  'JMD': 'Ямайский доллар',
  'JOD': 'Иорданский динар',
  'JPY': 'Японская иена',
  'KES': 'Кенийский шиллинг',
  'KGS': 'Сом',
  'KHR': 'Риель',
  'KMF': 'Франк Комор',
  'KPW': 'Северокорейская вона',
  'KRW': 'Вона',
  'KWD': 'Кувейтский динар',
  'KYD': 'Доллар Каймановых островов',
  'KZT': 'Тенге',
  'LAK': 'Кип Лаоса',
  'LBP': 'Ливанский фунт',
  'LKR': 'Шри-ланкийская рупия',
  'LRD': 'Либерийский доллар',
  'LSL': 'Лоти',
  'LYD': 'Ливийский динар',
  'MAD': 'Марокканский дирхам',
  'MDL': 'Молдавский лей',
  'MGA': 'Малагасийский ариари',
  'MKD': 'Денар',
  'MMK': 'Кьят',
  'MNT': 'Тугрик',
  'MOP': 'Патака',
  'MRU': 'Углия Мавритании',
  'MUR': 'Маврикийская рупия',
  'MVR': 'Руфия',
  'MWK': 'Квача Малави',
  'MXN': 'Мексиканское песо',
  'MYR': 'Малайзийский ринггит',
  'MZN': 'Метикал Мозамбика',
  'NAD': 'Доллар Намибии',
  'NGN': 'Наира',
  'NIO': 'Кордоба',
  'NOK': 'Норвежская крона',
  'NPR': 'Непальская рупия',
  'NZD': 'Новозеландский доллар',
  'OMR': 'Оманский риал',
  'PAB': 'Бальбоа',
  'PEN': 'Соль',
  'PGK': 'Кина',
  'PHP': 'Филиппинское песо',
  'PKR': 'Пакистанская рупия',
  'PLN': 'Злотый',
  'PYG': 'Гуарани',
  'QAR': 'Катарский риал',
  'RON': 'Румынский лей',
  'RSD': 'Сербский динар',
  'RUB': 'Российский рубль',
  'RWF': 'Франк Руанды',
  'SAR': 'Саудовский риял',
  'SBD': 'Доллар Соломоновых Островов',
  'SCR': 'Сейшельская рупия',
  'SDG': 'Суданский фунт',
  'SEK': 'Шведская крона',
  'SGD': 'Сингапурский доллар',
  'SHP': 'Фунт Святой Елены',
  'SLE': 'Леоне',
  'SOS': 'Сомалийский шиллинг',
  'SRD': 'Суринамский доллар',
  'SSP': 'Южносуданский фунт',
  'STN': 'Добра',
  'SVC': 'Сальвадорский колон',
  'SYP': 'Сирийский фунт',
  'SZL': 'Лилангени',
  'THB': 'Бат',
  'TJS': 'Сомони',
  'TMT': 'Новый туркменский манат',
  'TND': 'Тунисский динар',
  'TOP': 'Паанга',
  'TRY': 'Турецкая лира',
  'TTD': 'Доллар Тринидада и Тобаго',
  'TWD': 'Новый тайваньский доллар',
  'TZS': 'Танзанийский шиллинг',
  'UAH': 'Гривна',
  'UGX': 'Угандийский шиллинг',
  'USD': 'Доллар США',
  'UYU': 'Уругвайское песо',
  'UZS': 'Узбекский сум',
  'VED': 'Суверенный боливар',
  'VES': 'Суверенный боливар',
  'VND': 'Донг',
  'VUV': 'Вату',
  'WST': 'Тала',
  'XAF': 'Франк КФА BEAC',
  'XCD': 'Восточно-карибский доллар',
  'XOF': 'Франк КФА BCEAO',
  'XPF': 'Франк КФП',
  'YER': 'Йеменский риал',
  'ZAR': 'Рэнд',
  'ZMW': 'Замбийская квача',
  'ZWL': 'Зимбабвийский доллар',
};
